name: Check and Deploy
on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - '*.md'
  workflow_dispatch:
    inputs:
      deploy:
        description: "Set to 'true' to deploy to AWS ECS and CloudReactor"
        required: false
        default: "true"
      deployment_environment:
        description: "Environment to deploy to"
        required: false
        default: "staging"

jobs:
  check_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          # Should match version in the Dockerfile
          java-version: '17.0.2'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build and test with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
